import type { Database } from './types.ts';

export const DATABASES: Database[] = [
  {
    "database_name": "Academic Complete & Library Thing Book Cover Widget Package",
    "subject_coverage": "Books, Multidisciplinary",
    "content_types": ["ebook", "book"],
    "search_fields": ["Title", "Author", "Publisher", "Year"],
    "filters": ["Full Text", "Book", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 3,
    "notes": "Primarily ebooks; low chance for journal articles."
  },
  {
    "database_name": "Academic Search Complete - EBSCO",
    "subject_coverage": "Multidisciplinary, Library & Information Science",
    "content_types": ["article", "ebook", "dissertation"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "TI=\"{title}\" AND AU=\"{author}\" AND SO=\"{journal}\" AND PY={year}",
    "fallback_strategies": ["Title+Author", "Title only", "Author only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 2,
    "notes": "Strong general database; full text often available for LIS journals."
  },
  {
    "database_name": "Academic Video Online (ASAVON)",
    "subject_coverage": "Videos, Multidisciplinary",
    "content_types": ["video"],
    "search_fields": ["Title", "Creator", "Year"],
    "filters": ["Full Video", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Creator=\"{author}\"",
    "fallback_strategies": ["Title only"],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 3,
    "notes": "Not useful for journal articles."
  },
  {
    "database_name": "ACM Digital Library",
    "subject_coverage": "Computer Science, Engineering",
    "content_types": ["article", "conference paper"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\" AND Journal=\"{journal}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Mostly CS; not relevant for LIS articles."
  },
  {
    "database_name": "AlManhal",
    "subject_coverage": "Arabic Publications, Multidisciplinary",
    "content_types": ["article", "ebook", "dissertation"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "Arabic", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 2,
    "notes": "Good for Arabic-language journals and dissertations."
  },
  {
    "database_name": "American Society Of Civil Engineers (ASCE)",
    "subject_coverage": "Civil Engineering",
    "content_types": ["article", "conference paper"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Not relevant for LIS."
  },
  {
    "database_name": "American Society of Mechanical Engineers - ASME",
    "subject_coverage": "Mechanical Engineering",
    "content_types": ["article", "conference paper"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Not relevant for LIS."
  },
  {
    "database_name": "AraBase - Dar Al Mandumah",
    "subject_coverage": "Arabic Publications, Multidisciplinary",
    "content_types": ["article", "dissertation", "ebook"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "Arabic", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 2,
    "notes": "Good for Arabic-language journals."
  },
  {
    "database_name": "ASTM",
    "subject_coverage": "Engineering, Materials Science",
    "content_types": ["article", "standard"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Not relevant for LIS."
  },
  {
    "database_name": "Avery Index to Architectural Periodicals - EBSCO",
    "subject_coverage": "Architecture, Design",
    "content_types": ["article", "conference paper"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "TI=\"{title}\" AND AU=\"{author}\" AND SO=\"{journal}\" AND PY={year}",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Not relevant for LIS."
  },
  {
    "database_name": "Biological Science - Proquest",
    "subject_coverage": "Biology, Life Sciences",
    "content_types": ["article", "dissertation"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "\"{title}\" AND \"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Not relevant for LIS."
  },
  {
    "database_name": "Britannica",
    "subject_coverage": "Reference, General Knowledge",
    "content_types": ["encyclopedia_entry", "article"],
    "search_fields": ["Title", "Author", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "Title=\"{title}\"",
    "fallback_strategies": ["Title only"],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 3,
    "notes": "Encyclopedic entries; not peer-reviewed journals."
  },
  {
    "database_name": "Business Periodicals Global with ABI/Inform Global - Proquest",
    "subject_coverage": "Business, Economics",
    "content_types": ["article", "dissertation"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Not relevant for LIS."
  },
  {
    "database_name": "CAB Abstracts -CABI",
    "subject_coverage": "Agriculture, Life Sciences",
    "content_types": ["article", "dissertation"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": true,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Not relevant for LIS."
  },
  {
    "database_name": "CABI",
    "subject_coverage": "Agriculture, Life Sciences",
    "content_types": ["article", "dissertation"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": true,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Not relevant for LIS."
  },
  {
    "database_name": "Child-link",
    "subject_coverage": "Education, Child Studies",
    "content_types": ["article", "report"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 2,
    "notes": "Relevant for education and child studies; some overlap with LIS education articles."
  },
  {
    "database_name": "Compustat",
    "subject_coverage": "Finance, Economics",
    "content_types": ["dataset", "report"],
    "search_fields": ["Title", "Author", "Year"],
    "filters": ["Full Text", "English", "Year"],
    "syntax_template": "Title=\"{title}\"",
    "fallback_strategies": ["Title only"],
    "metadata_only": true,
    "early_view_supported": false,
    "priority": 3,
    "notes": "Financial datasets; not relevant for LIS."
  },
  {
    "database_name": "Detail Inspiration",
    "subject_coverage": "Architecture, Design",
    "content_types": ["article", "image", "report"],
    "search_fields": ["Title", "Author", "Year"],
    "filters": ["Full Text", "English", "Year"],
    "syntax_template": "Title=\"{title}\"",
    "fallback_strategies": ["Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Not relevant for LIS."
  },
  {
    "database_name": "Dissertation and Thesis - Proquest",
    "subject_coverage": "All subjects",
    "content_types": ["dissertation", "thesis"],
    "search_fields": ["Title", "Author", "University", "Year"],
    "filters": ["Full Text", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 2,
    "notes": "Great for finding full dissertations and theses."
  },
  {
    "database_name": "Ecolink - Dar Al Mandumah",
    "subject_coverage": "Environment, Arabic Publications",
    "content_types": ["article", "report"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "Arabic", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 3,
    "notes": "Not relevant for LIS."
  },
  {
    "database_name": "EconLit - EBSCO",
    "subject_coverage": "Economics, Business",
    "content_types": ["article", "report"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "TI=\"{title}\" AND AU=\"{author}\" AND SO=\"{journal}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Mostly economics-focused; not relevant for LIS."
  },
  {
    "database_name": "Education Abstracts - EBSCO",
    "subject_coverage": "Education, Library Science",
    "content_types": ["article", "report"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "TI=\"{title}\" AND AU=\"{author}\" AND SO=\"{journal}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 1,
    "notes": "Relevant for LIS articles in education journals."
  },
  {
    "database_name": "EduSearch - Dar Al Mandumah",
    "subject_coverage": "Education, Arabic Publications",
    "content_types": ["article", "dissertation"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "Arabic", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 2,
    "notes": "Good for Arabic-language education research."
  },
  {
    "database_name": "Elsevier Ebooks",
    "subject_coverage": "Science, Technology, Multidisciplinary",
    "content_types": ["ebook", "book"],
    "search_fields": ["Title", "Author", "Publisher", "Year"],
    "filters": ["Full Text", "Book", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 2,
    "notes": "Mostly ebooks; low chance for journal articles."
  },
  {
    "database_name": "Emarefa",
    "subject_coverage": "Arabic Academic Publications",
    "content_types": ["article", "dissertation"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "Arabic", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 2,
    "notes": "Good for Arabic-language academic articles."
  },
  {
    "database_name": "Emerald Elite",
    "subject_coverage": "Business, Management, Library Science",
    "content_types": ["article", "case study"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\" AND Journal=\"{journal}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 1,
    "notes": "Strong coverage of library & information science journals."
  },
  {
    "database_name": "Engineering Village - Elsevier",
    "subject_coverage": "Engineering, Technology",
    "content_types": ["article", "conference paper"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Not relevant for LIS."
  },
  {
    "database_name": "Environmental Design Research Association (EDRA)",
    "subject_coverage": "Architecture, Environmental Design",
    "content_types": ["article", "conference paper"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Not relevant for LIS."
  },
  {
    "database_name": "Environmental Impact - CABI",
    "subject_coverage": "Environment, Agriculture",
    "content_types": ["article", "report"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": true,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Not relevant for LIS."
  },
  {
    "database_name": "Eric - EBSCO",
    "subject_coverage": "Education, Library Science",
    "content_types": ["article", "report", "dissertation"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "TI=\"{title}\" AND AU=\"{author}\" AND SO=\"{journal}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 1,
    "notes": "Strong LIS coverage; use fallback strategies for early publications."
  },
  {
    "database_name": "General Science Abstracts - EBSCO",
    "subject_coverage": "Science, Multidisciplinary",
    "content_types": ["article", "report"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "TI=\"{title}\" AND AU=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Mostly science; limited relevance for LIS."
  },
  {
    "database_name": "Global Books in Print",
    "subject_coverage": "Books, Multidisciplinary",
    "content_types": ["book", "ebook"],
    "search_fields": ["Title", "Author", "Publisher", "Year"],
    "filters": ["Full Text", "Book", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 2,
    "notes": "Book database; may not have journal articles."
  },
  {
    "database_name": "Global Health - CABI",
    "subject_coverage": "Public Health, Life Sciences",
    "content_types": ["article", "report"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": true,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Not relevant for LIS."
  },
  {
    "database_name": "Global Health Archive - CABI",
    "subject_coverage": "Public Health, Life Sciences",
    "content_types": ["article", "report"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": true,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Not relevant for LIS."
  },
  {
    "database_name": "HeinOnline",
    "subject_coverage": "Law, Legal Studies",
    "content_types": ["article", "report", "case"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 2,
    "notes": "Strong for legal research; limited LIS relevance."
  },
  {
    "database_name": "Historical Abstracts - EBSCO",
    "subject_coverage": "History, Humanities",
    "content_types": ["article", "report"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "TI=\"{title}\" AND AU=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Not relevant for LIS."
  },
  {
    "database_name": "HumanIndex - Dar Al Mandumah",
    "subject_coverage": "Humanities, Arabic Publications",
    "content_types": ["article", "dissertation"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "Arabic", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 2,
    "notes": "Arabic-language humanities database."
  },
  {
    "database_name": "Humanities Abstracts - EBSCO",
    "subject_coverage": "Humanities",
    "content_types": ["article", "report"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "TI=\"{title}\" AND AU=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Not relevant for LIS."
  },
  {
    "database_name": "IBFD Tax Research",
    "subject_coverage": "Taxation, Finance",
    "content_types": ["article", "report"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Not relevant for LIS."
  },
  {
    "database_name": "IEEE",
    "subject_coverage": "Engineering, Technology",
    "content_types": ["article", "conference paper"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "Document Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Mostly engineering; limited LIS relevance."
  },
  {
    "database_name": "IGI Global - InfoSci e-books",
    "subject_coverage": "Information Science, Technology",
    "content_types": ["ebook", "book", "chapter"],
    "search_fields": ["Title", "Author", "Publisher", "Year"],
    "filters": ["Full Text", "Book", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 2,
    "notes": "Ebooks; chapters may be relevant for LIS research."
  },
  {
    "database_name": "IGI Global - InfoSci Journals",
    "subject_coverage": "Information Science, Library Science",
    "content_types": ["article", "case study"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\" AND Journal=\"{journal}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 1,
    "notes": "Strong coverage for LIS journals."
  },
  {
    "database_name": "Index Islamicus - EBSCO",
    "subject_coverage": "Islamic Studies, Humanities",
    "content_types": ["article", "book review"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "TI=\"{title}\" AND AU=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 2,
    "notes": "Relevant for Islamic studies; limited LIS relevance."
  },
  {
    "database_name": "Index to Legal Periodicals - EBSCO",
    "subject_coverage": "Law, Legal Studies",
    "content_types": ["article", "report", "case study"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "TI=\"{title}\" AND AU=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Not relevant for LIS."
  },
  {
    "database_name": "ISI Web of Science",
    "subject_coverage": "Multidisciplinary, Science, LIS",
    "content_types": ["article", "conference paper"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "TI=\"{title}\" AND AU=\"{author}\" AND SO=\"{journal}\" AND PY={year}",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 1,
    "notes": "One of the best for LIS and multidisciplinary research."
  },
  {
    "database_name": "Islamic Info - Dar Al Mandumah",
    "subject_coverage": "Arabic Islamic Studies",
    "content_types": ["article", "dissertation"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "Arabic", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 2,
    "notes": "Arabic content; not specifically LIS."
  },
  {
    "database_name": "JCR",
    "subject_coverage": "Journal Metrics, Multidisciplinary",
    "content_types": ["dataset", "report"],
    "search_fields": ["Title", "Journal", "Year"],
    "filters": ["Full Text", "English", "Year"],
    "syntax_template": "Journal=\"{journal}\" AND Title=\"{title}\"",
    "fallback_strategies": ["Title+Journal", "Title only"],
    "metadata_only": true,
    "early_view_supported": false,
    "priority": 2,
    "notes": "Used for journal metrics; not full articles."
  },
  {
    "database_name": "King Faisal Center for Research and Islamic Studies",
    "subject_coverage": "Arabic Studies, Islamic Studies",
    "content_types": ["article", "report", "book"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Arabic", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 2,
    "notes": "Arabic and Islamic studies; not LIS."
  },
  {
    "database_name": "Knovel",
    "subject_coverage": "Engineering, Applied Sciences",
    "content_types": ["ebook", "report"],
    "search_fields": ["Title", "Author", "Publisher", "Year"],
    "filters": ["Full Text", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Mostly engineering; limited LIS relevance."
  },
  {
    "database_name": "Legal Collection - EBSCO",
    "subject_coverage": "Law, Legal Studies",
    "content_types": ["article", "report", "case"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "TI=\"{title}\" AND AU=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Not relevant for LIS."
  },
  {
    "database_name": "Lexis+ UK (formerly Lexis Library)",
    "subject_coverage": "Law, Legal Studies",
    "content_types": ["article", "case", "report"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Legal database; not LIS."
  },
  {
    "database_name": "Lexis360",
    "subject_coverage": "Law, Legal Studies",
    "content_types": ["article", "case", "report"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Legal database; not LIS."
  },
  {
    "database_name": "Library and Information Sciences Abstracts (LISA Plus) - Proquest",
    "subject_coverage": "Library & Information Science",
    "content_types": ["article", "report"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "\"{title}\" AND \"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 1,
    "notes": "One of the top databases for LIS research."
  },
  {
    "database_name": "Library Literature & Information Science Index - EBSCO",
    "subject_coverage": "Library & Information Science",
    "content_types": ["article", "report"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "TI=\"{title}\" AND AU=\"{author}\" AND SO=\"{journal}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 1,
    "notes": "High-priority LIS database; fallback strategies recommended."
  },
  {
    "database_name": "Linguistics & Language Behavior Abstracts (LLBA)- Proquest",
    "subject_coverage": "Linguistics, Language, Communication",
    "content_types": ["article", "report"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "\"{title}\" AND \"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 2,
    "notes": "Relevant for language studies; may overlap with LIS research."
  },
  {
    "database_name": "MathSciNet - EBSCO",
    "subject_coverage": "Mathematics, Science",
    "content_types": ["article", "report"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "TI=\"{title}\" AND AU=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": true,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Mathematics database; not relevant for LIS."
  },
  {
    "database_name": "MLA International Bibliography - EBSCO",
    "subject_coverage": "Literature, Humanities, Language",
    "content_types": ["article", "report"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "TI=\"{title}\" AND AU=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 2,
    "notes": "Relevant for humanities; limited LIS relevance."
  },
  {
    "database_name": "Nexis Uni",
    "subject_coverage": "News, Business, Law",
    "content_types": ["article", "report", "news"],
    "search_fields": ["Title", "Author", "Source", "Year"],
    "filters": ["Full Text", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\" AND Source=\"{journal}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 3,
    "notes": "News and business focus; limited LIS."
  },
  {
    "database_name": "O'Reilly",
    "subject_coverage": "Technology, Programming",
    "content_types": ["ebook", "video", "report"],
    "search_fields": ["Title", "Author", "Publisher", "Year"],
    "filters": ["Full Text", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 3,
    "notes": "Primarily technology; limited LIS relevance."
  },
  {
    "database_name": "OnePetro",
    "subject_coverage": "Petroleum, Energy Engineering",
    "content_types": ["article", "conference paper"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Not relevant for LIS."
  },
  {
    "database_name": "Oxford Reference Online",
    "subject_coverage": "Reference, Multidisciplinary",
    "content_types": ["encyclopedia_entry", "article"],
    "search_fields": ["Title", "Author", "Year"],
    "filters": ["Full Text", "English", "Year"],
    "syntax_template": "Title=\"{title}\"",
    "fallback_strategies": ["Title only"],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 2,
    "notes": "Reference content; may supplement LIS research."
  },
  {
    "database_name": "Pollution Abstracts - EBSCO",
    "subject_coverage": "Environmental Science",
    "content_types": ["article", "report"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "TI=\"{title}\" AND AU=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 3,
    "notes": "Not relevant for LIS."
  },
  {
    "database_name": "Project Muse",
    "subject_coverage": "Humanities, Social Sciences",
    "content_types": ["article", "ebook"],
    "search_fields": ["Title", "Author", "Journal", "Year"],
    "filters": ["Full Text", "Article", "English", "Year"],
    "syntax_template": "Title=\"{title}\" AND Author=\"{author}\"",
    "fallback_strategies": ["Title+Author", "Title only"],
    "metadata_only": false,
    "early_view_supported": true,
    "priority": 2,
    "notes": "Humanities focus; some LIS relevance."
  },
  {
    "database_name": "Proquest Central",
    "subject_coverage": "",
    "content_types": [],
    "search_fields": [],
    "filters": [],
    "syntax_template": "",
    "fallback_strategies": [],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 3,
    "notes": ""
  },
  {
    "database_name": "Psycinfo - EBSCO",
    "subject_coverage": "",
    "content_types": [],
    "search_fields": [],
    "filters": [],
    "syntax_template": "",
    "fallback_strategies": [],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 3,
    "notes": ""
  },
  {
    "database_name": "Sage Premier",
    "subject_coverage": "",
    "content_types": [],
    "search_fields": [],
    "filters": [],
    "syntax_template": "",
    "fallback_strategies": [],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 3,
    "notes": ""
  },
  {
    "database_name": "Sage Research Methods",
    "subject_coverage": "",
    "content_types": [],
    "search_fields": [],
    "filters": [],
    "syntax_template": "",
    "fallback_strategies": [],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 3,
    "notes": ""
  },
  {
    "database_name": "Sage Videos",
    "subject_coverage": "",
    "content_types": [],
    "search_fields": [],
    "filters": [],
    "syntax_template": "",
    "fallback_strategies": [],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 3,
    "notes": ""
  },
  {
    "database_name": "Science Direct",
    "subject_coverage": "",
    "content_types": [],
    "search_fields": [],
    "filters": [],
    "syntax_template": "",
    "fallback_strategies": [],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 3,
    "notes": ""
  },
  {
    "database_name": "SciFinder",
    "subject_coverage": "",
    "content_types": [],
    "search_fields": [],
    "filters": [],
    "syntax_template": "",
    "fallback_strategies": [],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 3,
    "notes": ""
  },
  {
    "database_name": "Scival",
    "subject_coverage": "",
    "content_types": [],
    "search_fields": [],
    "filters": [],
    "syntax_template": "",
    "fallback_strategies": [],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 3,
    "notes": ""
  },
  {
    "database_name": "Scopus",
    "subject_coverage": "",
    "content_types": [],
    "search_fields": [],
    "filters": [],
    "syntax_template": "",
    "fallback_strategies": [],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 3,
    "notes": ""
  },
  {
    "database_name": "Social Sciences Journal",
    "subject_coverage": "",
    "content_types": [],
    "search_fields": [],
    "filters": [],
    "syntax_template": "",
    "fallback_strategies": [],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 3,
    "notes": ""
  },
  {
    "database_name": "Ulrich's Web",
    "subject_coverage": "",
    "content_types": [],
    "search_fields": [],
    "filters": [],
    "syntax_template": "",
    "fallback_strategies": [],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 3,
    "notes": ""
  },
  {
    "database_name": "Westlaw International Academic",
    "subject_coverage": "",
    "content_types": [],
    "search_fields": [],
    "filters": [],
    "syntax_template": "",
    "fallback_strategies": [],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 3,
    "notes": ""
  },
  {
    "database_name": "Westlaw UK Academic",
    "subject_coverage": "",
    "content_types": [],
    "search_fields": [],
    "filters": [],
    "syntax_template": "",
    "fallback_strategies": [],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 3,
    "notes": ""
  },
  {
    "database_name": "Wiley Reference Works",
    "subject_coverage": "",
    "content_types": [],
    "search_fields": [],
    "filters": [],
    "syntax_template": "",
    "fallback_strategies": [],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 3,
    "notes": ""
  },
  {
    "database_name": "الرسائل الجامعية (مؤسسة دار المنظومة)",
    "subject_coverage": "",
    "content_types": [],
    "search_fields": [],
    "filters": [],
    "syntax_template": "",
    "fallback_strategies": [],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 3,
    "notes": ""
  },
  {
    "database_name": "المعاهدات الدولية",
    "subject_coverage": "",
    "content_types": [],
    "search_fields": [],
    "filters": [],
    "syntax_template": "",
    "fallback_strategies": [],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 3,
    "notes": ""
  },
  {
    "database_name": "محامو الكويت",
    "subject_coverage": "",
    "content_types": [],
    "search_fields": [],
    "filters": [],
    "syntax_template": "",
    "fallback_strategies": [],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 3,
    "notes": ""
  },
  {
    "database_name": "محامون - موسوعة الأحكام القضائية العربية",
    "subject_coverage": "",
    "content_types": [],
    "search_fields": [],
    "filters": [],
    "syntax_template": "",
    "fallback_strategies": [],
    "metadata_only": false,
    "early_view_supported": false,
    "priority": 3,
    "notes": ""
  },
];